// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udxyksngdwzndalhfwdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkeHlrc25nZHd6bmRhbGhmd2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTY4ODMsImV4cCI6MjA1OTA5Mjg4M30.gf_yIeEzaQ1860hgygqoPnv5W5fjsKJgRl717YGF968";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);